[package]
name = "retrotool"
description = "Tools for working with Retro game formats."
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
publish = false
repository = "https://github.com/encounter/retrotool"
readme = "README.md"
categories = ["command-line-utilities"]

[profile.release]
lto = "thin"
panic = "abort"
strip = "debuginfo"

[dependencies]
anyhow = "1.0.69"
argh = "0.1.10"
binrw = "0.11.1"
binrw_derive = "0.11.1"
byteorder = "1.4.3"
env_logger = "0.10.0"
log = "0.4.17"
memmap2 = "0.5.8"
uuid = "1.3.0"
