[package]
name = "retrotool-gui"
description = "Tools for working with Retro game formats."
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
publish = false
repository = "https://github.com/PrimeDecomp/retrotool"
readme = "README.md"

[features]
default = []
dynamic = ["bevy/dynamic"]

[dependencies]
anyhow = "1.0.69"
astc-decode = "0.3.1"
bevy = "0.9.1"
bevy_egui = { git = "https://github.com/paul-hansen/bevy_egui", branch = "egui-0.21" }
binrw = "0.11.1"
egui = "0.21.0"
egui_dock = "0.4.0"
image = "0.24.5"
log = "0.4.17"
retrolib = { path = "../lib" }
uuid = "1.3.0"
walkdir = "2.3.2"
