[package]
name = "retrotool-gui"
description = "Tools for working with Retro game formats."
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
publish = false
repository = "https://github.com/PrimeDecomp/retrotool"
readme = "README.md"

[features]
default = []
dynamic = ["bevy/dynamic_linking"]

[dependencies]
anyhow = "1.0.69"
astc-decode = "0.3.1"
bevy = "0.10.0"
bevy_egui = { git = "https://github.com/encounter/bevy_egui", rev = "5cdfb4510511e17703562dfd41dc66909a4ab58a" }
binrw = "0.11.1"
bytemuck = "1.13.0"
egui = "0.21.0"
egui_dock = "0.4.0"
half = "2.2.1"
image = "0.24.5"
log = "0.4.17"
num-traits = "0.2.15"
retrolib = { path = "../lib" }
uuid = "1.3.0"
walkdir = "2.3.2"
