name: Build

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  pull_request:

env:
  CARGO_BIN_NAME: retrotool retrotool-gui
  CARGO_TARGET_DIR: target

jobs:
  check:
    name: Check
    env:
      RUSTFLAGS: -D warnings
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            packages: libasound2-dev
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.packages != ''
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cargo check
        run: cargo check
      - name: Cargo clippy
        run: cargo clippy

  deny:
    name: Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
      fail-fast: false
    # Prevent new advisories from failing CI
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}

  test:
    name: Test
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            packages: libasound2-dev
          - platform: windows-latest
          - platform: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.packages != ''
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo test
        run: cargo test --release

  build-cli:
    name: Build (CLI)
    env:
      CARGO_BIN_NAME: retrotool
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: linux-x86_64
            build: zigbuild
          - platform: ubuntu-latest
            target: i686-unknown-linux-musl
            name: linux-x86
            build: zigbuild
          - platform: ubuntu-latest
            target: aarch64-unknown-linux-musl
            name: linux-aarch64
            build: zigbuild
          - platform: ubuntu-latest
            target: armv7-unknown-linux-musleabi
            name: linux-armv7l
            build: zigbuild
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
            build: build
          - platform: windows-latest
            target: aarch64-pc-windows-msvc
            name: windows-arm64
            build: build
          - platform: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
            build: build
          - platform: macos-latest
            target: aarch64-apple-darwin
            name: macos-arm64
            build: build
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.packages != ''
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: Install cargo-zigbuild
        if: matrix.build == 'zigbuild'
        run: pip install cargo-zigbuild
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Cargo build
        run: cargo ${{ matrix.build }} --release --target ${{ matrix.target }} --bin ${{ env.CARGO_BIN_NAME }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ env.CARGO_TARGET_DIR }}/release/${{ env.CARGO_BIN_NAME }}
            ${{ env.CARGO_TARGET_DIR }}/release/${{ env.CARGO_BIN_NAME }}.exe
            ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/release/${{ env.CARGO_BIN_NAME }}
            ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/release/${{ env.CARGO_BIN_NAME }}.exe
          if-no-files-found: error

  build:
    name: Build (GUI)
    env:
      CARGO_BIN_NAME: retrotool-gui
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
            build: build
            packages: libasound2-dev
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            name: windows-x86_64
            build: build
          - platform: windows-latest
            target: aarch64-pc-windows-msvc
            name: windows-arm64
            build: build
          - platform: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
            build: build
          - platform: macos-latest
            target: aarch64-apple-darwin
            name: macos-arm64
            build: build
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        if: matrix.packages != ''
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ${{ matrix.packages }}
      - name: Install cargo-zigbuild
        if: matrix.build == 'zigbuild'
        run: pip install cargo-zigbuild
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Cargo build
        run: cargo ${{ matrix.build }} --release --target ${{ matrix.target }} --bin ${{ env.CARGO_BIN_NAME }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: |
            ${{ env.CARGO_TARGET_DIR }}/release/${{ env.CARGO_BIN_NAME }}
            ${{ env.CARGO_TARGET_DIR }}/release/${{ env.CARGO_BIN_NAME }}.exe
            ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/release/${{ env.CARGO_BIN_NAME }}
            ${{ env.CARGO_TARGET_DIR }}/${{ matrix.target }}/release/${{ env.CARGO_BIN_NAME }}.exe
          if-no-files-found: error

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Rename artifacts
        working-directory: artifacts
        run: |
          mkdir ../out
          for bin in $CARGO_BIN_NAME; do
            for i in */*/release/$bin{,.exe}; do
              if [ -f "$i" ]; do
                mv "$i" "../out/$(sed -E "s/([^/]+)\/[^/]+\/release\/($bin)/\2-\1/" <<< "$i")"
              fi
            done
          done
          ls -R ../out
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
